foo = "foo"
bar = "{{foo/rafb/rfoa/raor}}"
baz = "{{bar/rarz}}"
puf = "{{baz/rabp/raau/razf}}"
baf = "{{puf/rapb/raua}}"
mof = "{{baf/rabm/raao}}"

uuu = "{{foo/rafu/raou}}"
vvv = "{{uuu/ravv}}-{{bar/rabv/raav/rarv}}"
www = "{{vvv/raww}}-{{baf/rabw/raaw/rafw}}"
xxx = "{{www/raxx}}-{{baz/rabx/raax/razx}}"
yyy = "{{xxx/rayy}}-{{mof/ramy/raoy/rafy}}"
zzz = "{{yyy/razz}}-{{puf/rapz/rauz/rafz}}"

zzzz-date-time = "Date {{mold-date-ISO_Date}} and time {{mold-date-ISO_Time}}"
zzzz-date_time = "{{zzzz-date-time/ra-_}}"      #  replace all '-' with '_'
