name = "mold"
description = "Meta-variable Operations for Lean Development"
version = "0.1.0-dev"

authors = ["Francesc Rocher"]
maintainers = ["Francesc Rocher <francesc.rocher@gmail.com>"]
maintainers-logins = ["rocher"]

executables = ["mold"]
licenses = "MIT"

[build-profiles]
"mold" = "development"

[build-switches."*"]
ada_version = ["-gnat2022", "-gnatX"]

[[depends-on]]
clic = "~0.2.1"
simple_logging = "^1.2.0"
curl = "^7.81.0"
spdx = "~0.2.0"
