Fibonacci = '''
    This is a multiline literal definition of a paragraph in TOML format.
    It's useful for a long descriptions, paragraphs with displays:

        a_1 = 1
        a_2 = 1
        a_n = a_{n-1} + a_{n-2}

    and the like. It'll be used a lot for things like this.'''

par01 = '''Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Sem et tortor consequat
id porta nibh. Arcu felis bibendum ut tristique et egestas quis. Quam
adipiscing vitae proin sagittis nisl rhoncus. Eu ultrices vitae auctor
eu. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant
morbi. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Cras
ornare arcu dui vivamus arcu felis. Feugiat in fermentum posuere urna nec
tincidunt praesent semper feugiat. Venenatis a condimentum vitae sapien
pellentesque habitant morbi tristique senectus. Non quam lacus suspendisse
faucibus interdum posuere lorem ipsum. Ac felis donec et odio
pellentesque. Ut enim blandit volutpat maecenas. Turpis nunc eget lorem dolor
sed viverra ipsum nunc. Varius morbi enim nunc faucibus a pellentesque sit
amet. Sit amet mattis vulputate enim nulla. Quisque sagittis purus sit amet
volutpat consequat mauris nunc. Dolor magna eget est lorem ipsum dolor.'''

par02 = '''Volutpat blandit aliquam etiam erat velit scelerisque. Luctus accumsan tortor
posuere ac ut consequat semper. Mauris ultrices eros in cursus turpis
massa. Lorem sed risus ultricies tristique. Et malesuada fames ac turpis
egestas integer eget. Laoreet non curabitur gravida arcu ac. Nulla porttitor
massa id neque aliquam vestibulum. Varius duis at consectetur lorem donec. In
nisl nisi scelerisque eu ultrices vitae auctor eu augue. Blandit libero
volutpat sed cras ornare arcu dui. Orci sagittis eu volutpat odio facilisis
mauris sit. Rhoncus est pellentesque elit ullamcorper dignissim cras
tincidunt. Scelerisque fermentum dui faucibus in ornare quam viverra orci
sagittis. Ipsum dolor sit amet consectetur adipiscing elit duis.'''

par03 = '''In nulla posuere sollicitudin aliquam ultrices sagittis orci a
scelerisque. Sed euismod nisi porta lorem mollis aliquam ut porttitor
leo. Rutrum quisque non tellus orci ac auctor augue mauris augue. At varius
vel pharetra vel. Dolor sit amet consectetur adipiscing elit. Tempus egestas
sed sed risus pretium. Lectus vestibulum mattis ullamcorper velit sed
ullamcorper. Lorem ipsum dolor sit amet consectetur. Lorem donec massa sapien
faucibus et. Sagittis purus sit amet volutpat consequat mauris nunc congue
nisi. Ornare arcu dui vivamus arcu felis bibendum ut. Diam sit amet nisl
suscipit adipiscing bibendum est. Viverra accumsan in nisl nisi scelerisque
eu ultrices vitae auctor. Est lorem ipsum dolor sit amet consectetur
adipiscing. Ullamcorper velit sed ullamcorper morbi. Amet aliquam id diam
maecenas ultricies mi eget. Dis parturient montes nascetur ridiculus mus.'''
