Day = "1"
Year = "{{mold-date-%Y}}"

Author = "Name Surname"
Email = "your.email@example.com"
Github_Username = "username"
Github_Repository = "advent_of_code-{{Year}}"
Address = "{{Author}} <{{Email}}>"
ZDay = "{{Day/pl02}}"
License = "MIT"
