a = "arcu"
b = "bibendum"
c = "commodo"
d = "dolor"
e = "elementum"
eg = "egestas"
f = "faucibus"
g = "gravida"
h = "habitant"
i = "in"
int = "integer"
j = "justo"
l = "lorem"
L = "Lorem"
m = "massa"
ni = "nibh"
n = "nulla"
o = "orci"
p = "proin"
p2 = "pellentesque"
q = "quis"
r = "risus"
s = "scelerisque"
t = "tristique"
u = "ut"
v = "viverra"
